version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  graphql:
    image: node:carbon
    build: .
    ports:
      - "7777:7777"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ~/node-graphql-react:/data/db
    command: mongod --bind_ip 0.0.0.0
